version: '3.8'

services:
  db:
    image: postgres:17.5-alpine
    container_name: covid-board-db
    restart: always
    environment:
      POSTGRES_DB: covid_board
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
